apiVersion: v1
kind: ReplicationController
metadata:
  name: app_my
  labels:
    name: myapp
spec:
  template:
    metadata:
      metadata:
        name: nginx
        labels:
          name: nginx
      spec:
        containers:
          - name: nginx
            image: nginx
  replicas: 3