apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2020-05-04T18:03:11Z"
    name: ubuntu-sleeper
    namespace: default
    resourceVersion: "544"
    selfLink: /api/v1/namespaces/default/pods/ubuntu-sleeper
    uid: 56b51897-d370-4676-a23a-0f12aac2ca73
  spec:
    securityContext:
      runAsUser: 1000
    containers:
    - command:
      - sleep
      - "4800"
      image: ubuntu
      imagePullPolicy: Always
      name: ubuntu
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-7vtkb
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: node01
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: default-token-7vtkb
      secret:
        defaultMode: 420
        secretName: default-token-7vtkb
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2020-05-04T18:03:11Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2020-05-04T18:03:17Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2020-05-04T18:03:17Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2020-05-04T18:03:11Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://5efdc5d230841c5aa03456efddd430160e8415e483408ab9f5dac3fd958e2ef1
      image: ubuntu:latest
      imageID: docker-pullable://ubuntu@sha256:747d2dbbaaee995098c9792d99bd333c6783ce56150d1b11e333bbceed5c54d7
      lastState: {}
      name: ubuntu
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2020-05-04T18:03:16Z"
    hostIP: 172.17.0.37
    phase: Running
    podIP: 10.88.0.3
    podIPs:
    - ip: 10.88.0.3
    qosClass: BestEffort
    startTime: "2020-05-04T18:03:11Z"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""