#help https://phoenixnap.com/kb/how-to-install-jenkins-kubernetes

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: jenkins
  name: jenkins
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30008
  selector:
    app: jenkins
  type: NodePort
status:
  loadBalancer: {}