apiVersion: apps/v1
kind:  Deployment
metadata:
  name: wepapp
  labels:
    app: myapp
    type: fronend
spec:
  template:
    metadata:
      name: myapp=pod
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx

  selector:
    matchLabels:
      app: myapp
  replicas: 4x