apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-05-05T09:07:29Z"
  generation: 1
  name: web-dashboard
  namespace: default
  resourceVersion: "1319"
  selfLink: /apis/apps/v1/namespaces/default/deployments/web-dashboard
  uid: 33a73700-f6a4-4ac9-a217-517321bf874f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: web-dashboard
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: web-dashboard
    spec:
      containers:
      - image: kodekloud/my-kubernetes-dashboard
        imagePullPolicy: Always
        name: web-dashboard
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccount: dashboard-sa
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-05-05T09:07:37Z"
    lastUpdateTime: "2020-05-05T09:07:37Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-05-05T09:07:29Z"
    lastUpdateTime: "2020-05-05T09:07:37Z"
    message: ReplicaSet "web-dashboard-854bffb74f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1