apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: db

  name: db
spec:
  replicas: 1
  selector:
    matchLabels:

      app: db

  template:
    metadata:
      creationTimestamp: null
      labels:
        app: db


    spec:
      volumes:
        - name: db-data
          emptyDir: {}

      containers:

      - image: postgres:9.4
        name: postgres
        env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
        ports:
        - containerPort: 5432
        resources: {}

        volumeMounts:
          - name: db-data
            mountPath: /var/lib/postgresql/data

status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: db
  name: db
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432

  selector:
    app: demo-voting-app
    name: db
  type: ClusterIP