apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: db
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:

      app: demo-voting-app
      name: db-deployment

  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo-voting-app
        name: db-deployment
    spec:
      volumes:
        - name: db-data
          emptyDir: {}

      containers:

      - image: postgres:9.4
        name: db-deployment
        ports:
        - containerPort: 5432
        resources: {}
        env:
          - name: POSTGRES_PASSWORD
            value: password
        volumeMounts:
          - name: db-data
            mountPath: /var/lib/postgresql/data

status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: db
  name: db
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432

  selector:
    app: demo-voting-app
    name: db-deployment
  type: ClusterIP