apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:

      app: radis


  template:
    metadata:
      creationTimestamp: null
      labels:
        app: radis


    spec:
      volumes:
        - name: redis-data
          emptyDir: {}

      containers:
      - image: redis
        name: redis
        ports:
        - containerPort: 6379
        resources: {}
        volumeMounts:
          - name: redis-data
            mountPath: /data

status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: redis
  name: redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379

  selector:
    app: radis

  type: ClusterIP