apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vote-app

  name: vote-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-app


  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vote-app


    spec:
      containers:
      - image: dockersamples/examplevotingapp_vote
        name: vote-app
        ports:
        - containerPort: 80
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: vote-app
  name: vote-app
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 80
    nodePort: 31000
  selector:
    app: vote-app

  type: NodePort