apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vote-deployment

  name: vote-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-voting-app
      name: vote-deployment

  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo-voting-app
        name: vote-deployment
      name: vote-deployment
    spec:
      containers:
      - image: dockersamples/examplevotingapp_vote
        name: voting-app
        ports:
        - containerPort: 80
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: vote-deployment
  name: vote-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 80
    nodePort: 31000
  selector:
    app: demo-voting-app
    name: vote-deployment
  type: NodePort