apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx

spec:
  volumes:
    - name: demofile
      secret:
        secretName: app-secret

  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    volumeMounts:
     - name: demofile
       mountPath: /mydata
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
