apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
  namespace: myexample
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    envFrom:
      - configMapRef:
          name: myexample

    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
